// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjfM6JaElwq-ttWIOnNHHBixzn9y438ZI',
    appId: '1:101703302103:web:81680bb9ac218e3825e992',
    messagingSenderId: '101703302103',
    projectId: 'you-tube-2dc42',
    authDomain: 'you-tube-2dc42.firebaseapp.com',
    storageBucket: 'you-tube-2dc42.appspot.com',
    measurementId: 'G-NS3C1VKE7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6mVPn-9XUvTeKcXlGE_BXnsYbcKDWzXk',
    appId: '1:101703302103:android:46666db1cd0ec52825e992',
    messagingSenderId: '101703302103',
    projectId: 'you-tube-2dc42',
    storageBucket: 'you-tube-2dc42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJW0xizo_cuJ9spBr3ekGHBj1YGcJijZY',
    appId: '1:101703302103:ios:de65e81604c1ea3325e992',
    messagingSenderId: '101703302103',
    projectId: 'you-tube-2dc42',
    storageBucket: 'you-tube-2dc42.appspot.com',
    iosBundleId: 'com.example.youTube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJW0xizo_cuJ9spBr3ekGHBj1YGcJijZY',
    appId: '1:101703302103:ios:de65e81604c1ea3325e992',
    messagingSenderId: '101703302103',
    projectId: 'you-tube-2dc42',
    storageBucket: 'you-tube-2dc42.appspot.com',
    iosBundleId: 'com.example.youTube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjfM6JaElwq-ttWIOnNHHBixzn9y438ZI',
    appId: '1:101703302103:web:3af93d3cb686129125e992',
    messagingSenderId: '101703302103',
    projectId: 'you-tube-2dc42',
    authDomain: 'you-tube-2dc42.firebaseapp.com',
    storageBucket: 'you-tube-2dc42.appspot.com',
    measurementId: 'G-4LDC019GGW',
  );
}
